# Generated by Django 3.2.25 on 2025-03-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='wishlist',
        ),
    ]
