# Generated by Django 3.2.25 on 2025-03-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
